name: openfootball_fixtures_yaml
description: English premier league fixtures builder.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.0.0
  freezed: ^0.14.0+1
  dio: ^4.0.0-beta7
  equatable: ^2.0.0
  riverpod: ^0.13.1

dev_dependencies:
  pedantic: ^1.11.0
  build_runner:
